// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3L_lD_i96NsgHBSvVPTnTfzJ7GHvVWc',
    appId: '1:262599958579:web:1857b61e60e87c5f81c346',
    messagingSenderId: '262599958579',
    projectId: 'cadastro-clientes-teste-naka',
    authDomain: 'cadastro-clientes-teste-naka.firebaseapp.com',
    storageBucket: 'cadastro-clientes-teste-naka.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWXbBc_5jP59cMQj8mXH9VS1n-BNEE9SE',
    appId: '1:262599958579:android:95c93cee638b239b81c346',
    messagingSenderId: '262599958579',
    projectId: 'cadastro-clientes-teste-naka',
    storageBucket: 'cadastro-clientes-teste-naka.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSHl6yuwLHlO05zkwnX3jRjzfxvTaPUN4',
    appId: '1:262599958579:ios:e465906b5550d7a981c346',
    messagingSenderId: '262599958579',
    projectId: 'cadastro-clientes-teste-naka',
    storageBucket: 'cadastro-clientes-teste-naka.appspot.com',
    iosClientId: '262599958579-up5a1ip9a5cjdhad20guq7cjcms7gqcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cadClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSHl6yuwLHlO05zkwnX3jRjzfxvTaPUN4',
    appId: '1:262599958579:ios:e465906b5550d7a981c346',
    messagingSenderId: '262599958579',
    projectId: 'cadastro-clientes-teste-naka',
    storageBucket: 'cadastro-clientes-teste-naka.appspot.com',
    iosClientId: '262599958579-up5a1ip9a5cjdhad20guq7cjcms7gqcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cadClientes',
  );
}
